### ISSUE TITLE
Unknown error bei Kalender Optionen

### ISSUE THREAD

**Issue by GitGramm** [JonasJoKuJonas/homeassistant-WebUntis#151]
### The problem

Vielen Dank für das schnelle fixen des uid-Bugs!
Hab nun noch ein weiteren Bug entdeckt:
Wenn ich die Option "Kalender-Ort" auf Short Name ändere kommt ein Unknown error.
Auch andere Optionen lassen sich nicht speichern:
![image](https://github.com/user-attachments/assets/f07a4201-76b4-466c-883e-8e2757ddae4e)

Habe auf die letzten Version von HA und WebUntis upgedated, meine davor hätte es funktioniert, bin mir aber nicht sicher...

### Version of Home Assistant?

2024.9.2

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v1.2.5

**Comment by JonasJoKuJonas** [comment]
Bekommst du irgendein Fehler in den Logs?

**Comment by GitGramm** [comment]
Evtl ist das hier relevant:
2024-09-18 13:41:23.004 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/config_flow.py", line 494, in async_step_calendar
    _LOGGER.info(user_input["calendar_replace_name"])
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'calendar_replace_name'

**Comment by JonasJoKuJonas** [comment]
das ist noch eine debbug Nachricht. Die sollte da nicht mehr sein.
Benutze einmal kurz den Ereignisnamen ersetzen. Dann sollte es wieder gehen (temp fix bis zum nächsten update)

**Comment by JonasJoKuJonas** [comment]
fixed in v1.2.6

**Comment by GitGramm** [comment]
Mit dem Quickfix geht es und sobald sie im HACS verfügbar ist, installiere ich 1.2.6! Vielen Dank!
