### ISSUE TITLE
v1.3.1: Fehler bei der Einrichtung

### ISSUE THREAD

**Issue by matspi** [JonasJoKuJonas/homeassistant-WebUntis#163]
### The problem

Nach Update auf v1.3.1 werden keine Daten mehr angezeigt.
Stattdessen nur noch
> Fehler beim Einrichten:

Traceback ist unten angehängt.

### Version of Home Assistant?

2024.10.1

### What type of installation are you running?

Home Assistant Core

### Version of WebUntis

v1.3.1

### Traceback/Error logs

```
Traceback (most recent call last):
KeyError: 'result'


Traceback (most recent call last):
  File "/config/custom_components/webuntis/__init__.py", line 1018, in get_lesson_for_notify
    for teacher in lesson.teachers
                   ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/webuntis/utils/misc.py", line 30, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/webuntis/objects.py", line 344, in teachers
    return self._session.teachers(from_cache=True).filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/webuntis/utils/misc.py", line 156, in inner
    data = self._request(jsonrpc_method, jsonrpc_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/webuntis/session.py", line 124, in _request
    data = rpc_request(self.config, method, params or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/webuntis/utils/remote.py", line 91, in rpc_request
    return _parse_result(request_body, result_body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/webuntis/utils/remote.py", line 125, in _parse_result
    _parse_error_code(request_body, result_body)
  File "/usr/local/lib/python3.12/site-packages/webuntis/utils/remote.py", line 143, in _parse_error_code
    raise exc
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    await server.async_update()
  File "/config/custom_components/webuntis/__init__.py", line 264, in async_update
    await self._async_status_request()
  File "/config/custom_components/webuntis/__init__.py", line 403, in _async_status_request
    self.calendar_events = await self._hass.async_add_executor_job(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 709, in _get_events
    self.event_list.append(self.get_lesson_for_notify(lesson))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self.exclude_data_("teachers")
  File "/config/custom_components/webuntis/__init__.py", line 1039, in exclude_data_
  File "/usr/src/homeassistant/homeassistant/core.py", line 462, in verify_event_loop_thread
    frame.report_non_thread_safe_operation(what)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 229, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 163, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 201, in _report_integration
RuntimeError: Detected that custom integration 'webuntis' calls hass.config_entries.async_update_entry from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassconfig_entriesasync_update_entry at custom_components/webuntis/__init__.py, line 1039: self._hass.config_entries.async_update_entry(self._config, options=new_options). Please report it to the author of the 'webuntis' custom integration.
```

**Comment by matspi** [comment]
Löschen der Integration und neu Hinzufügen löst das Problem.
