### ISSUE TITLE
keine aktuellen Daten - log deutet auf Lehrer - ist aber ausgeschlossen

### ISSUE THREAD

**Issue by evilmumi** [JonasJoKuJonas/homeassistant-WebUntis#166]
Ich hatte mich gewundert, warum keine Infos mehr zu Ausfällen kamen, obwohl der notify test funktioniert.
Im Log fand ich dies:

### The problem

Log:
`2024-10-25 13:39:18.327 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/webuntis/__init__.py", line 264, in async_update
    await self._async_status_request()
  File "/config/custom_components/webuntis/__init__.py", line 496, in _async_status_request
    await self.update_notify()
  File "/config/custom_components/webuntis/__init__.py", line 1073, in update_notify
    changes = get_changes(change, lesson, lesson_old, server=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/notify.py", line 238, in get_changes
    server=server, name=name, teacher=lesson["teachers"][0]["name"]`

### Version of Home Assistant?

2024.10.3

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

1.3.1

### Traceback/Error logs
![image](https://github.com/user-attachments/assets/88434d96-87b2-43f1-9e8b-02295b208ebe)

**Comment by JonasJoKuJonas** [comment]
fixed in v1.3.2
