### ISSUE TITLE
No rooms found

### ISSUE THREAD

**Issue by joe050860** [JonasJoKuJonas/homeassistant-WebUntis#39]
Hallo Jonas, kannst du damit was anfangen. Guten Rutsch!

xxx steht für meinen Benutzernamen.

2022-12-31 09:27:59.430 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx for webuntis
File "/config/custom_components/webuntis/__init__.py", line 52, in async_setup_entry
server = WebUntis(hass, unique_id, entry)
File "/config/custom_components/webuntis/__init__.py", line 134, in __init__
2022-12-31 09:29:10.610 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx for webuntis
File "/config/custom_components/webuntis/__init__.py", line 52, in async_setup_entry
server = WebUntis(hass, unique_id, entry)
File "/config/custom_components/webuntis/__init__.py", line 134, in __init__
2022-12-31 09:29:32.784 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx for webuntis
File "/config/custom_components/webuntis/__init__.py", line 54, in async_setup_entry
File "/config/custom_components/webuntis/__init__.py", line 178, in async_update
File "/config/custom_components/webuntis/__init__.py", line 268, in _async_status_request
File "/config/custom_components/webuntis/__init__.py", line 423, in _get_events
File "/usr/local/lib/python3.10/site-packages/webuntis/objects.py", line 180, in __getitem__

**Comment by JonasJoKuJonas** [comment]
Kannst du die komplette Fehlermeldung (Traceback) posten? 

[![Open your Home Assistant instance and show your Home Assistant logs.](https://my.home-assistant.io/badges/logs.svg)](https://my.home-assistant.io/redirect/logs/)

**Comment by assineu** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/webuntis/__init__.py", line 54, in async_setup_entry
    await server.async_update()
  File "/config/custom_components/webuntis/__init__.py", line 178, in async_update
    await self._async_status_request()
  File "/config/custom_components/webuntis/__init__.py", line 268, in _async_status_request
    self.calendar_events = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/webuntis/__init__.py", line 423, in _get_events
    location=lesson.rooms[0].long_name,  # add Room as location
  File "/usr/local/lib/python3.10/site-packages/webuntis/objects.py", line 180, in __getitem__
    data = self._data[i]  # fails if there is no such item

**Comment by JonasJoKuJonas** [comment]
should be working in version v0.3.5
