### ISSUE TITLE
Error setting up entry Klassenplan for webuntis

### ISSUE THREAD

**Issue by TaxmanNo1** [JonasJoKuJonas/homeassistant-WebUntis#45]
### The problem

Hallo,
ich habe ohne Probleme den Stundenplan der Klasse 11 (Leistungskurssystem im Gymnasium) einrichten können, aber nicht den (für meinen Sohn richtigen) Stundenplan der Klasse 06b.
Es erscheint die Fehlermeldung "Error setting up entry Klassenplan for webuntis" und folgende Protokolldetails:

### Version of Home Assistant?

2023.1.6

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v0.3.5

### Traceback/Error logs

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/webuntis/__init__.py:432
Integration: Web Untis (documentation, issues)
First occurred: 17:49:31 (2 occurrences)
Last logged: 17:49:57

Error setting up entry Klassenplan for webuntis
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/webuntis/__init__.py", line 54, in async_setup_entry
    await server.async_update()
  File "/config/custom_components/webuntis/__init__.py", line 178, in async_update
    await self._async_status_request()
  File "/config/custom_components/webuntis/__init__.py", line 268, in _async_status_request
    self.calendar_events = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/webuntis/__init__.py", line 432, in _get_events
    if lesson.rooms:
  File "/usr/local/lib/python3.10/site-packages/webuntis/utils/misc.py", line 30, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/usr/local/lib/python3.10/site-packages/webuntis/objects.py", line 352, in rooms
    return self._session.rooms(from_cache=True).filter(
  File "/usr/local/lib/python3.10/site-packages/webuntis/objects.py", line 163, in filter
    data=[self.filter(**{key: v})[0]
  File "/usr/local/lib/python3.10/site-packages/webuntis/objects.py", line 163, in <listcomp>
    data=[self.filter(**{key: v})[0]
  File "/usr/local/lib/python3.10/site-packages/webuntis/objects.py", line 180, in __getitem__
    data = self._data[i]  # fails if there is no such item
IndexError: list index out of range

**Comment by JonasJoKuJonas** [comment]
solle in v0.4.1 funktionieren

**Comment by TaxmanNo1** [comment]
Läuft... Danke
