### ISSUE TITLE
Problems with WebUntis integration

### ISSUE THREAD

**Issue by GodzillaTV** [JonasJoKuJonas/homeassistant-WebUntis#98]
### The problem

Hello, unfortunately the first problem still exists. In addition, a few more problems have now arisen.

1.
Logger: homeassistant.components.discord.notify
Source: components/discord/notify.py:124
Integration: Discord (documentation, issues)
First occurred: 8. November 2023 um 05:51:34 (4 occurrences)
Last logged: 9. November 2023 um 09:26:36

No target specified

2.
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: webuntis
Source: custom_components/webuntis/__init__.py:373
Integration: Web Untis (documentation, issues)
First occurred: 7. November 2023 um 22:01:32 (4 occurrences)
Last logged: 8. November 2023 um 21:21:33

{'jsonrpc': '2.0', 'id': '2023-11-07 22:01:32.252213', 'error': {'message': 'not authenticated', 'code': -8520}}
{'jsonrpc': '2.0', 'id': '2023-11-08 08:41:32.393843', 'error': {'message': 'not authenticated', 'code': -8520}}
{'jsonrpc': '2.0', 'id': '2023-11-08 18:06:32.527143', 'error': {'message': 'not authenticated', 'code': -8520}}
{'jsonrpc': '2.0', 'id': '2023-11-08 21:21:32.572263', 'error': {'message': 'not authenticated', 'code': -8520}}

3.
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.webuntis
Source: custom_components/webuntis/__init__.py:344
Integration: Web Untis (documentation, issues)
First occurred: 9. November 2023 um 09:16:36 (1 occurrences)
Last logged: 9. November 2023 um 09:16:36

Updating the property today-sensor of '{school}@{username}' failed - OSError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

4.
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Source: custom_components/webuntis/__init__.py:373
Integration: Web Untis (documentation, issues)
First occurred: 8. November 2023 um 21:16:37 (1 occurrences)
Last logged: 8. November 2023 um 21:16:37

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8406c290>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='perseus.webuntis.com', port=443): Max retries exceeded with url: /WebUntis/jsonrpc.do?school=Hubertus-Schwartz-BK (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8406c290>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/webuntis/__init__.py", line 206, in async_update
    await self._async_status_request()
  File "/config/custom_components/webuntis/__init__.py", line 214, in _async_status_request
    suggess = await self._hass.async_add_executor_job(self.webuntis_login)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/webuntis/__init__.py", line 373, in webuntis_login
    self.session.schoolyears()
  File "/usr/local/lib/python3.11/site-packages/webuntis/utils/misc.py", line 156, in inner
    data = self._request(jsonrpc_method, jsonrpc_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/webuntis/session.py", line 118, in _request
    data = rpc_request(self.config, method, params or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/webuntis/utils/remote.py", line 85, in rpc_request
    result_body = _send_request(
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/webuntis/utils/remote.py", line 154, in _send_request
    r = http_session.post(url, data=json.dumps(data), headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='perseus.webuntis.com', port=443): Max retries exceeded with url: /WebUntis/jsonrpc.do?school=Hubertus-Schwartz-BK (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8406c290>: Failed to establish a new connection: [Errno -3] Try again'))

### Version of Home Assistant?

core-2023.11.1

### What type of installation are you running?

Home Assistant OS

### Version of WebUntis

v1.0.2

**Comment by JonasJoKuJonas** [comment]
This error is caused by the WebUntis API. Deactivate the integration for a day, and then it should work again. If the issue persists, please reopen the issue.
